using System;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PacketWire.Generator;

/// <summary>
/// Emits strongly typed serialization codecs for packet models and nested contracts discovered by the source generator.
/// </summary>
internal static class GeneratedCodecEmitter
{
    /// <summary>
    /// Specifies the symbol display format used when emitting fully qualified C# type references in generated codecs.
    /// </summary>
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <summary>
    /// Computes the unique Roslyn source hint name for the generated codec file corresponding to the specified wire type symbol.
    /// </summary>
    /// <param name="wireType">The named type symbol representing the wire type.</param>
    /// <returns>A stable string hint name suitable for <c>SourceProductionContext.AddSource</c>.</returns>
    internal static string GetHintName(
        INamedTypeSymbol wireType)
    {
        string identity =
            wireType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);

        string sanitized =
            SanitizeIdentifier(
                wireType.Name);

        ulong hash =
            ComputeStableHash(identity);

        return
            "PacketWire." +
            sanitized +
            "." +
            hash.ToString(
                "X16",
                CultureInfo.InvariantCulture) +
            ".g.cs";
    }

    /// <summary>
    /// Emits the complete C# source text for the static codec class that serializes and deserializes the specified wire type model.
    /// </summary>
    /// <param name="model">The wire type model describing the packet or contract and its ordered fields.</param>
    /// <returns>A <see cref="SourceText"/> instance containing the generated codec source code.</returns>
    internal static SourceText Emit(
        WireTypeModel model)
    {
        StringBuilder builder =
            new();

        string typeName =
            GetTypeName(
                model.WireType);

        string codecName =
            GetCodecClassName(
                model.WireType);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace PacketWire.Generated");
        builder.AppendLine("{");
        builder.Append("    internal static class ");
        builder.AppendLine(codecName);
        builder.AppendLine("    {");

        EmitValidationMethod(
            builder,
            model,
            typeName);

        EmitLengthMethod(
            builder,
            model,
            typeName);

        EmitWriteMethod(
            builder,
            model,
            typeName);

        EmitReadMethod(
            builder,
            model,
            typeName);

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return SourceText.From(
            builder.ToString(),
            Encoding.UTF8);
    }

    /// <summary>
    /// Computes the deterministic, collision-free C# identifier for the static codec class generated for the specified wire type.
    /// </summary>
    /// <param name="wireType">The named type symbol representing the wire type.</param>
    /// <returns>A string identifier for the generated codec class.</returns>
    internal static string GetCodecClassName(
        INamedTypeSymbol wireType)
    {
        string identity =
            wireType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);

        string sanitized =
            SanitizeIdentifier(
                wireType.Name);

        ulong hash =
            ComputeStableHash(identity);

        return
            "__PacketWireCodec_" +
            sanitized +
            "_" +
            hash.ToString(
                "X16",
                CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// Emits the <c>ValidateValue</c> private helper method into the generated codec class to enforce non-null invariants on reference-type fields.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="model">The wire type model describing the fields to validate.</param>
    /// <param name="typeName">The fully qualified name of the wire type being validated.</param>
    private static void EmitValidationMethod(
        StringBuilder builder,
        WireTypeModel model,
        string typeName)
    {
        builder.Append(
            "        private static void ValidateValue(");

        builder.Append(typeName);
        builder.AppendLine(" value)");
        builder.AppendLine("        {");

        if (model.WireType.IsReferenceType)
        {
            builder.AppendLine(
                "            if (value is null)");

            builder.AppendLine("            {");

            builder.AppendLine(
                "                throw new global::System.ArgumentNullException(nameof(value));");

            builder.AppendLine("            }");
        }

        foreach (PacketFieldModel field in model.Fields)
        {
            if (field.IsOptional ||
                !IsReferenceLikeField(field))
            {
                continue;
            }

            builder.Append("            if (value.@");
            builder.Append(field.Property.Name);
            builder.AppendLine(" is null)");
            builder.AppendLine("            {");

            builder.Append(
                "                throw new global::System.InvalidOperationException(\"Packet field '");

            builder.Append(field.Property.Name);

            builder.AppendLine(
                "' is non-nullable but contains null.\");");

            builder.AppendLine("            }");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
    }

    /// <summary>
    /// Emits the <c>GetEncodedLength</c> internal method calculating the exact encoded byte length of a wire type instance.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="model">The wire type model describing the fields and serialization rules.</param>
    /// <param name="typeName">The fully qualified name of the wire type.</param>
    private static void EmitLengthMethod(
        StringBuilder builder,
        WireTypeModel model,
        string typeName)
    {
        builder.Append(
            "        internal static int GetEncodedLength(");

        builder.Append(typeName);
        builder.AppendLine(" value,");

        builder.AppendLine(
            "            global::PacketWire.PacketProtocolDefinition definition)");

        builder.AppendLine("        {");
        builder.AppendLine("            ValidateValue(value);");
        builder.AppendLine(
            "            global::System.ArgumentNullException.ThrowIfNull(definition);");

        builder.AppendLine();
        builder.AppendLine("            int length = 0;");

        foreach (PacketFieldModel field in model.Fields)
        {
            builder.AppendLine();

            if (field.IsOptional)
            {
                builder.AppendLine(
                    "            length = checked(length + 1);");

                string presenceExpression =
                    GetPresenceExpression(field);

                builder.Append("            if (");
                builder.Append(presenceExpression);
                builder.AppendLine(")");
                builder.AppendLine("            {");

                EmitLengthForValue(
                    builder,
                    field,
                    GetPresentValueExpression(field),
                    "                ");

                builder.AppendLine("            }");
            }
            else
            {
                EmitLengthForValue(
                    builder,
                    field,
                    GetPropertyExpression(field),
                    "            ");
            }
        }

        builder.AppendLine();
        builder.AppendLine("            return length;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    /// <summary>
    /// Emits code to accumulate the byte length contributed by an individual field value (scalar, fixed string, collection, or nested contract).
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="field">The model of the packet field being measured.</param>
    /// <param name="valueExpression">The C# expression referencing the field value.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    private static void EmitLengthForValue(
        StringBuilder builder,
        PacketFieldModel field,
        string valueExpression,
        string indent)
    {
        if (field.Shape
            == PacketFieldShape.Sequence)
        {
            string countName =
                "__count_" +
                field.Order.ToString(
                    CultureInfo.InvariantCulture);

            builder.Append(indent);
            builder.Append("int ");
            builder.Append(countName);
            builder.Append(" = ");
            builder.Append(valueExpression);
            builder.Append(
                field.ValueType is IArrayTypeSymbol
                    ? ".Length;"
                    : ".Count;");

            builder.AppendLine();

            builder.Append(indent);
            builder.Append(
                "length = checked(length + global::PacketWire.PacketCollectionCodec.GetEncodedCountLength(");

            builder.Append(countName);
            builder.Append(", definition");

            AppendMaximumCountArgument(
                builder,
                field);

            builder.AppendLine("));");

            ITypeSymbol elementType =
                field.ElementType
                ?? throw new InvalidOperationException(
                    "A sequence field does not expose an element type.");

            if (TryGetFixedByteLength(
                    elementType,
                    field.FixedStringByteLength,
                    out int fixedElementLength))
            {
                builder.Append(indent);
                builder.Append(
                    "length = checked(length + checked(");

                builder.Append(countName);
                builder.Append(" * ");

                builder.Append(
                    fixedElementLength.ToString(
                        CultureInfo.InvariantCulture));

                builder.AppendLine("));");

                return;
            }

            string itemName =
                "__item_" +
                field.Order.ToString(
                    CultureInfo.InvariantCulture);

            builder.Append(indent);
            builder.Append("foreach (");
            builder.Append(GetTypeName(elementType));
            builder.Append(' ');
            builder.Append(itemName);
            builder.Append(" in ");
            builder.Append(valueExpression);
            builder.AppendLine(")");
            builder.Append(indent);
            builder.AppendLine("{");

            EmitReferenceElementNullGuard(
                builder,
                elementType,
                itemName,
                field.Property.Name,
                indent + "    ");

            builder.Append(indent);
            builder.Append(
                "    length = checked(length + ");

            builder.Append(
                GetNestedCodecName(
                    elementType));

            builder.Append(".GetEncodedLength(");
            builder.Append(itemName);
            builder.AppendLine(", definition));");

            builder.Append(indent);
            builder.AppendLine("}");

            return;
        }

        if (field.Shape
            == PacketFieldShape.NestedContract)
        {
            builder.Append(indent);
            builder.Append(
                "length = checked(length + ");

            builder.Append(
                GetNestedCodecName(
                    field.ValueType));

            builder.Append(".GetEncodedLength(");
            builder.Append(valueExpression);
            builder.AppendLine(", definition));");

            return;
        }

        int fixedLength =
            GetFixedByteLength(field);

        builder.Append(indent);
        builder.Append(
            "length = checked(length + ");

        builder.Append(
            fixedLength.ToString(
                CultureInfo.InvariantCulture));

        builder.AppendLine(");");
    }

    /// <summary>
    /// Emits the <c>Write</c> internal method that serializes all fields of a wire type instance to a <c>PacketWriter</c>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="model">The wire type model describing the fields and serialization rules.</param>
    /// <param name="typeName">The fully qualified name of the wire type.</param>
    private static void EmitWriteMethod(
        StringBuilder builder,
        WireTypeModel model,
        string typeName)
    {
        builder.AppendLine(
            "        internal static void Write(");

        builder.AppendLine(
            "            ref global::PacketWire.PacketWriter writer,");

        builder.Append("            ");
        builder.Append(typeName);
        builder.AppendLine(" value,");

        builder.AppendLine(
            "            global::PacketWire.PacketProtocolDefinition definition)");

        builder.AppendLine("        {");
        builder.AppendLine("            ValidateValue(value);");
        builder.AppendLine(
            "            global::System.ArgumentNullException.ThrowIfNull(definition);");

        foreach (PacketFieldModel field in model.Fields)
        {
            builder.AppendLine();

            if (field.IsOptional)
            {
                string presenceExpression =
                    GetPresenceExpression(field);

                builder.Append(
                    "            bool __present_");

                builder.Append(
                    field.Order.ToString(
                        CultureInfo.InvariantCulture));

                builder.Append(" = ");
                builder.Append(presenceExpression);
                builder.AppendLine(";");

                builder.Append(
                    "            global::PacketWire.PacketPresenceCodec.Write(ref writer, __present_");

                builder.Append(
                    field.Order.ToString(
                        CultureInfo.InvariantCulture));

                builder.AppendLine(");");

                builder.Append("            if (__present_");

                builder.Append(
                    field.Order.ToString(
                        CultureInfo.InvariantCulture));

                builder.AppendLine(")");
                builder.AppendLine("            {");

                EmitWriteValue(
                    builder,
                    field,
                    GetPresentValueExpression(field),
                    "                ");

                builder.AppendLine("            }");
            }
            else
            {
                EmitWriteValue(
                    builder,
                    field,
                    GetPropertyExpression(field),
                    "            ");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine();
    }

    /// <summary>
    /// Emits code to serialize a field value, handling sequence collections and dispatching to element writers.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="field">The model of the packet field being serialized.</param>
    /// <param name="valueExpression">The C# expression representing the field value.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    private static void EmitWriteValue(
        StringBuilder builder,
        PacketFieldModel field,
        string valueExpression,
        string indent)
    {
        if (field.Shape
            == PacketFieldShape.Sequence)
        {
            string countExpression =
                valueExpression +
                (field.ValueType is IArrayTypeSymbol
                    ? ".Length"
                    : ".Count");

            builder.Append(indent);
            builder.Append(
                "global::PacketWire.PacketCollectionCodec.WriteCount(ref writer, ");

            builder.Append(countExpression);
            builder.Append(", definition");

            AppendMaximumCountArgument(
                builder,
                field);

            builder.AppendLine(");");

            ITypeSymbol elementType =
                field.ElementType
                ?? throw new InvalidOperationException(
                    "A sequence field does not expose an element type.");

            string itemName =
                "__item_" +
                field.Order.ToString(
                    CultureInfo.InvariantCulture);

            builder.Append(indent);
            builder.Append("foreach (");
            builder.Append(GetTypeName(elementType));
            builder.Append(' ');
            builder.Append(itemName);
            builder.Append(" in ");
            builder.Append(valueExpression);
            builder.AppendLine(")");
            builder.Append(indent);
            builder.AppendLine("{");

            EmitReferenceElementNullGuard(
                builder,
                elementType,
                itemName,
                field.Property.Name,
                indent + "    ");

            EmitWriteElement(
                builder,
                elementType,
                field.FixedStringByteLength,
                itemName,
                indent + "    ");

            builder.Append(indent);
            builder.AppendLine("}");

            return;
        }

        EmitWriteElement(
            builder,
            field.ValueType,
            field.FixedStringByteLength,
            valueExpression,
            indent,
            field.Shape);
    }

    /// <summary>
    /// Emits code to serialize an individual element or scalar field using the appropriate writer method or nested codec.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="type">The type symbol of the element being serialized.</param>
    /// <param name="fixedStringByteLength">The optional fixed byte count if the element is a fixed text string.</param>
    /// <param name="valueExpression">The C# expression representing the element value.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    /// <param name="explicitShape">The explicit field shape override if known, otherwise inferred from type.</param>
    private static void EmitWriteElement(
        StringBuilder builder,
        ITypeSymbol type,
        int? fixedStringByteLength,
        string valueExpression,
        string indent,
        PacketFieldShape? explicitShape = null)
    {
        PacketFieldShape shape =
            explicitShape
            ?? GetElementShape(type);

        if (shape == PacketFieldShape.FixedText)
        {
            builder.Append(indent);
            builder.Append(
                "writer.WriteFixedString(");

            builder.Append(valueExpression);
            builder.Append(", ");

            builder.Append(
                fixedStringByteLength
                    ?.ToString(
                        CultureInfo.InvariantCulture)
                ?? throw new InvalidOperationException(
                    "A fixed string field does not expose a byte length."));

            builder.AppendLine(");");

            return;
        }

        if (shape
            == PacketFieldShape.NestedContract)
        {
            builder.Append(indent);

            builder.Append(
                GetNestedCodecName(type));

            builder.Append(".Write(ref writer, ");
            builder.Append(valueExpression);
            builder.AppendLine(", definition);");

            return;
        }

        if (shape
            == PacketFieldShape.EnumerationValue)
        {
            INamedTypeSymbol enumType =
                (INamedTypeSymbol)type;

            ITypeSymbol underlyingType =
                enumType.EnumUnderlyingType
                ?? throw new InvalidOperationException(
                    "An enum field does not expose an underlying type.");

            builder.Append(indent);
            builder.Append("writer.");
            builder.Append(
                GetWriteMethod(
                    underlyingType));

            builder.Append("((");

            builder.Append(
                GetPrimitiveTypeKeyword(
                    underlyingType));

            builder.Append(')');
            builder.Append(valueExpression);
            builder.AppendLine(");");

            return;
        }

        builder.Append(indent);
        builder.Append("writer.");

        builder.Append(
            GetWriteMethod(type));

        builder.Append('(');
        builder.Append(valueExpression);
        builder.AppendLine(");");
    }

    /// <summary>
    /// Emits the <c>Read</c> internal method that deserializes a wire type instance from a <c>PacketReader</c>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="model">The wire type model describing the fields to decode.</param>
    /// <param name="typeName">The fully qualified name of the wire type being read.</param>
    private static void EmitReadMethod(
        StringBuilder builder,
        WireTypeModel model,
        string typeName)
    {
        builder.Append("        internal static ");
        builder.Append(typeName);
        builder.AppendLine(" Read(");

        builder.AppendLine(
            "            ref global::PacketWire.PacketReader reader,");

        builder.AppendLine(
            "            global::PacketWire.PacketProtocolDefinition definition)");

        builder.AppendLine("        {");

        builder.AppendLine(
            "            global::System.ArgumentNullException.ThrowIfNull(definition);");

        foreach (PacketFieldModel field in model.Fields)
        {
            builder.AppendLine();

            string fieldName =
                "__field_" +
                field.Order.ToString(
                    CultureInfo.InvariantCulture);

            builder.Append("            ");
            builder.Append(
                GetTypeName(
                    field.Property.Type));

            builder.Append(' ');
            builder.Append(fieldName);
            builder.AppendLine(";");

            if (field.IsOptional)
            {
                builder.AppendLine(
                    "            if (global::PacketWire.PacketPresenceCodec.Read(ref reader))");

                builder.AppendLine("            {");

                EmitReadValueAssignment(
                    builder,
                    field,
                    fieldName,
                    "                ");

                builder.AppendLine("            }");
                builder.AppendLine("            else");
                builder.AppendLine("            {");
                builder.Append("                ");
                builder.Append(fieldName);
                builder.AppendLine(" = null;");
                builder.AppendLine("            }");
            }
            else
            {
                EmitReadValueAssignment(
                    builder,
                    field,
                    fieldName,
                    "            ");
            }
        }

        builder.AppendLine();

        builder.Append("            return new ");
        builder.Append(typeName);
        builder.AppendLine();
        builder.AppendLine("            {");

        foreach (PacketFieldModel field in model.Fields)
        {
            builder.Append("                @");
            builder.Append(field.Property.Name);
            builder.Append(" = __field_");

            builder.Append(
                field.Order.ToString(
                    CultureInfo.InvariantCulture));

            builder.AppendLine(",");
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
    }

    /// <summary>
    /// Emits the assignment statement that reads an individual field value from the reader and assigns it to a target variable.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="field">The model of the packet field being decoded.</param>
    /// <param name="targetName">The variable identifier receiving the decoded value.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    private static void EmitReadValueAssignment(
        StringBuilder builder,
        PacketFieldModel field,
        string targetName,
        string indent)
    {
        if (field.Shape
            == PacketFieldShape.Sequence)
        {
            EmitReadCollection(
                builder,
                field,
                targetName,
                indent);

            return;
        }

        builder.Append(indent);
        builder.Append(targetName);
        builder.Append(" = ");

        EmitReadElementExpression(
            builder,
            field.ValueType,
            field.FixedStringByteLength,
            field.Shape);

        builder.AppendLine(";");
    }

    /// <summary>
    /// Emits code to read collection items prefixed by their count into an array or list based on the field definition.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="field">The model of the collection packet field.</param>
    /// <param name="targetName">The variable identifier receiving the instantiated collection.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    private static void EmitReadCollection(
        StringBuilder builder,
        PacketFieldModel field,
        string targetName,
        string indent)
    {
        ITypeSymbol elementType =
            field.ElementType
            ?? throw new InvalidOperationException(
                "A sequence field does not expose an element type.");

        string countName =
            "__count_" +
            field.Order.ToString(
                CultureInfo.InvariantCulture);

        builder.Append(indent);
        builder.Append("int ");
        builder.Append(countName);

        builder.Append(
            " = global::PacketWire.PacketCollectionCodec.ReadCount(ref reader, definition");

        AppendMaximumCountArgument(
            builder,
            field);

        builder.AppendLine(");");

        if (field.ValueType is IArrayTypeSymbol)
        {
            string arrayName =
                "__items_" +
                field.Order.ToString(
                    CultureInfo.InvariantCulture);

            builder.Append(indent);

            builder.Append(
                GetTypeName(elementType));

            builder.Append("[] ");
            builder.Append(arrayName);
            builder.Append(" = new ");

            builder.Append(
                GetTypeName(elementType));

            builder.Append('[');
            builder.Append(countName);
            builder.AppendLine("];");

            builder.Append(indent);
            builder.Append("for (int __index_");

            builder.Append(
                field.Order.ToString(
                    CultureInfo.InvariantCulture));

            builder.Append(" = 0; __index_");

            builder.Append(
                field.Order.ToString(
                    CultureInfo.InvariantCulture));

            builder.Append(" < ");
            builder.Append(countName);
            builder.Append("; __index_");

            builder.Append(
                field.Order.ToString(
                    CultureInfo.InvariantCulture));

            builder.AppendLine("++)");

            builder.Append(indent);
            builder.AppendLine("{");

            builder.Append(indent);
            builder.Append("    ");
            builder.Append(arrayName);
            builder.Append("[__index_");

            builder.Append(
                field.Order.ToString(
                    CultureInfo.InvariantCulture));

            builder.Append("] = ");

            EmitReadElementExpression(
                builder,
                elementType,
                field.FixedStringByteLength,
                GetElementShape(elementType));

            builder.AppendLine(";");

            builder.Append(indent);
            builder.AppendLine("}");

            builder.Append(indent);
            builder.Append(targetName);
            builder.Append(" = ");
            builder.Append(arrayName);
            builder.AppendLine(";");

            return;
        }

        string listName =
            "__items_" +
            field.Order.ToString(
                CultureInfo.InvariantCulture);

        string elementTypeName =
            GetTypeName(elementType);

        builder.Append(indent);

        builder.Append(
            "global::System.Collections.Generic.List<");

        builder.Append(elementTypeName);
        builder.Append("> ");
        builder.Append(listName);

        builder.Append(
            " = new global::System.Collections.Generic.List<");

        builder.Append(elementTypeName);
        builder.Append(">(");
        builder.Append(countName);
        builder.AppendLine(");");

        builder.Append(indent);
        builder.Append("for (int __index_");

        builder.Append(
            field.Order.ToString(
                CultureInfo.InvariantCulture));

        builder.Append(" = 0; __index_");

        builder.Append(
            field.Order.ToString(
                CultureInfo.InvariantCulture));

        builder.Append(" < ");
        builder.Append(countName);
        builder.Append("; __index_");

        builder.Append(
            field.Order.ToString(
                CultureInfo.InvariantCulture));

        builder.AppendLine("++)");

        builder.Append(indent);
        builder.AppendLine("{");

        builder.Append(indent);
        builder.Append("    ");
        builder.Append(listName);
        builder.Append(".Add(");

        EmitReadElementExpression(
            builder,
            elementType,
            field.FixedStringByteLength,
            GetElementShape(elementType));

        builder.AppendLine(");");

        builder.Append(indent);
        builder.AppendLine("}");

        builder.Append(indent);
        builder.Append(targetName);
        builder.Append(" = ");
        builder.Append(listName);
        builder.AppendLine(";");
    }

    /// <summary>
    /// Emits an expression to read an individual scalar, fixed string, nested contract, or enum value from the reader.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="type">The type symbol of the element being read.</param>
    /// <param name="fixedStringByteLength">The optional fixed string byte length constraint.</param>
    /// <param name="shape">The structural shape of the field or element.</param>
    private static void EmitReadElementExpression(
        StringBuilder builder,
        ITypeSymbol type,
        int? fixedStringByteLength,
        PacketFieldShape shape)
    {
        if (shape
            == PacketFieldShape.FixedText)
        {
            builder.Append(
                "reader.ReadFixedString(");

            builder.Append(
                fixedStringByteLength
                    ?.ToString(
                        CultureInfo.InvariantCulture)
                ?? throw new InvalidOperationException(
                    "A fixed string field does not expose a byte length."));

            builder.Append(')');

            return;
        }

        if (shape
            == PacketFieldShape.NestedContract)
        {
            builder.Append(
                GetNestedCodecName(type));

            builder.Append(
                ".Read(ref reader, definition)");

            return;
        }

        if (shape
            == PacketFieldShape.EnumerationValue)
        {
            INamedTypeSymbol enumType =
                (INamedTypeSymbol)type;

            ITypeSymbol underlyingType =
                enumType.EnumUnderlyingType
                ?? throw new InvalidOperationException(
                    "An enum field does not expose an underlying type.");

            builder.Append('(');
            builder.Append(GetTypeName(enumType));
            builder.Append(")reader.");

            builder.Append(
                GetReadMethod(
                    underlyingType));

            builder.Append("()");

            return;
        }

        builder.Append("reader.");

        builder.Append(
            GetReadMethod(type));

        builder.Append("()");
    }

    /// <summary>
    /// Emits a guard statement verifying that an element within a reference-typed collection is not null, throwing <see cref="InvalidOperationException"/> if violated.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="elementType">The element type symbol being inspected.</param>
    /// <param name="itemName">The variable identifier holding the item instance.</param>
    /// <param name="propertyName">The name of the packet property holding the collection.</param>
    /// <param name="indent">The indentation string for formatting emitted code.</param>
    private static void EmitReferenceElementNullGuard(
        StringBuilder builder,
        ITypeSymbol elementType,
        string itemName,
        string propertyName,
        string indent)
    {
        if (!elementType.IsReferenceType)
        {
            return;
        }

        builder.Append(indent);
        builder.Append("if (");
        builder.Append(itemName);
        builder.AppendLine(" is null)");

        builder.Append(indent);
        builder.AppendLine("{");

        builder.Append(indent);

        builder.Append(
            "    throw new global::System.InvalidOperationException(\"Collection packet field '");

        builder.Append(propertyName);

        builder.AppendLine(
            "' contains a null element.\");");

        builder.Append(indent);
        builder.AppendLine("}");
    }

    /// <summary>
    /// Determines whether the specified packet field requires a reference-type null check when non-optional.
    /// </summary>
    /// <param name="field">The model of the packet field.</param>
    /// <returns><see langword="true"/> if the field is a reference type or reference container; otherwise, <see langword="false"/>.</returns>
    private static bool IsReferenceLikeField(
        PacketFieldModel field)
    {
        if (field.Shape
            is PacketFieldShape.FixedText
            or PacketFieldShape.Sequence)
        {
            return true;
        }

        return
            field.Shape == PacketFieldShape.NestedContract &&
            field.ValueType.IsReferenceType;
    }

    /// <summary>
    /// Constructs the C# member access expression for reading a property on the packet value instance.
    /// </summary>
    /// <param name="field">The model of the packet field.</param>
    /// <returns>A string expression referencing the property.</returns>
    private static string GetPropertyExpression(
        PacketFieldModel field)
    {
        return
            "value.@" +
            field.Property.Name;
    }

    /// <summary>
    /// Constructs the C# boolean expression indicating whether an optional field has a present value.
    /// </summary>
    /// <param name="field">The model of the packet field.</param>
    /// <returns>A boolean expression string checking presence.</returns>
    private static string GetPresenceExpression(
        PacketFieldModel field)
    {
        string property =
            GetPropertyExpression(field);

        return IsNullableValueType(
                field.Property.Type)
            ? property + ".HasValue"
            : property + " is not null";
    }

    /// <summary>
    /// Constructs the C# expression accessing the unwrapped underlying value of a present optional field.
    /// </summary>
    /// <param name="field">The model of the packet field.</param>
    /// <returns>An unwrapped value expression string.</returns>
    private static string GetPresentValueExpression(
        PacketFieldModel field)
    {
        string property =
            GetPropertyExpression(field);

        return IsNullableValueType(
                field.Property.Type)
            ? property + ".Value"
            : property + "!";
    }

    /// <summary>
    /// Determines whether the given type symbol represents a nullable value type (<see cref="Nullable{T}"/>).
    /// </summary>
    /// <param name="type">The type symbol to check.</param>
    /// <returns><see langword="true"/> if the type is <see cref="Nullable{T}"/>; otherwise, <see langword="false"/>.</returns>
    private static bool IsNullableValueType(
        ITypeSymbol type)
    {
        return type is INamedTypeSymbol namedType &&
            namedType.IsGenericType &&
            namedType.TypeArguments.Length == 1 &&
            namedType.OriginalDefinition.MetadataName
                == "Nullable`1" &&
            namedType.OriginalDefinition.ContainingNamespace
                .ToDisplayString()
                == "System";
    }

    /// <summary>
    /// Appends the optional maximum count argument to an emitted collection codec call if a limit was declared.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> accumulating generated source code.</param>
    /// <param name="field">The model of the packet field.</param>
    private static void AppendMaximumCountArgument(
        StringBuilder builder,
        PacketFieldModel field)
    {
        if (!field.MaximumCount.HasValue)
        {
            return;
        }

        builder.Append(", ");

        builder.Append(
            field.MaximumCount.Value.ToString(
                CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// Resolves the serialization structural shape for an element type inside a collection or sequence.
    /// </summary>
    /// <param name="type">The type symbol of the collection element.</param>
    /// <returns>The resolved <see cref="PacketFieldShape"/>.</returns>
    private static PacketFieldShape GetElementShape(
        ITypeSymbol type)
    {
        if (type.SpecialType
            == SpecialType.System_String)
        {
            return PacketFieldShape.FixedText;
        }

        if (type.TypeKind
            == TypeKind.Enum)
        {
            return PacketFieldShape.EnumerationValue;
        }

        if (HasPacketContract(type))
        {
            return PacketFieldShape.NestedContract;
        }

        return PacketFieldShape.Scalar;
    }

    /// <summary>
    /// Determines whether the specified type symbol is decorated with the packet contract attribute.
    /// </summary>
    /// <param name="type">The type symbol to inspect.</param>
    /// <returns><see langword="true"/> if decorated with <c>PacketContractAttribute</c>; otherwise, <see langword="false"/>.</returns>
    private static bool HasPacketContract(
        ITypeSymbol type)
    {
        foreach (
            AttributeData attribute
            in type.GetAttributes())
        {
            if (attribute.AttributeClass
                    ?.ToDisplayString()
                == GeneratorMetadataNames.PacketContractAttribute)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Resolves the generated static codec class name for a nested contract type.
    /// </summary>
    /// <param name="type">The type symbol of the nested contract.</param>
    /// <returns>The class name of the generated codec for the nested contract.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the type is not a named type symbol.</exception>
    private static string GetNestedCodecName(
        ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            throw new InvalidOperationException(
                $"Nested packet contract '{type.ToDisplayString()}' is not a named type.");
        }

        return GetCodecClassName(namedType);
    }

    /// <summary>
    /// Attempts to determine the fixed byte length for a primitive, enum, or fixed string element.
    /// </summary>
    /// <param name="type">The type symbol to measure.</param>
    /// <param name="fixedStringByteLength">The optional fixed string byte length constraint.</param>
    /// <param name="byteLength">When this method returns, contains the fixed byte length if determined; otherwise, zero.</param>
    /// <returns><see langword="true"/> if the type has a constant fixed byte length; otherwise, <see langword="false"/>.</returns>
    private static bool TryGetFixedByteLength(
        ITypeSymbol type,
        int? fixedStringByteLength,
        out int byteLength)
    {
        if (type.SpecialType
            == SpecialType.System_String)
        {
            if (!fixedStringByteLength.HasValue)
            {
                byteLength = 0;
                return false;
            }

            byteLength =
                fixedStringByteLength.Value;

            return true;
        }

        if (type.TypeKind
            == TypeKind.Enum)
        {
            ITypeSymbol underlyingType =
                ((INamedTypeSymbol)type)
                    .EnumUnderlyingType
                ?? throw new InvalidOperationException(
                    "An enum field does not expose an underlying type.");

            byteLength =
                GetPrimitiveByteLength(
                    underlyingType);

            return true;
        }

        if (IsPrimitive(type))
        {
            byteLength =
                GetPrimitiveByteLength(type);

            return true;
        }

        byteLength = 0;
        return false;
    }

    /// <summary>
    /// Computes the fixed byte length for a fixed-size scalar or fixed text string field.
    /// </summary>
    /// <param name="field">The model of the packet field.</param>
    /// <returns>The fixed byte length of the field on the wire.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the field does not have a fixed size.</exception>
    private static int GetFixedByteLength(
        PacketFieldModel field)
    {
        if (field.Shape
            == PacketFieldShape.FixedText)
        {
            return field.FixedStringByteLength
                ?? throw new InvalidOperationException(
                    "A fixed string field does not expose a byte length.");
        }

        ITypeSymbol type =
            field.Shape
                == PacketFieldShape.EnumerationValue
                    ? ((INamedTypeSymbol)field.ValueType)
                        .EnumUnderlyingType
                        ?? throw new InvalidOperationException(
                            "An enum field does not expose an underlying type.")
                    : field.ValueType;

        return GetPrimitiveByteLength(type);
    }

    /// <summary>
    /// Returns the wire size in bytes for a primitive numeric or boolean type.
    /// </summary>
    /// <param name="type">The primitive type symbol.</param>
    /// <returns>The size in bytes.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the primitive type is unsupported.</exception>
    private static int GetPrimitiveByteLength(
        ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Byte => 1,
            SpecialType.System_SByte => 1,
            SpecialType.System_Int16 => 2,
            SpecialType.System_UInt16 => 2,
            SpecialType.System_Int32 => 4,
            SpecialType.System_UInt32 => 4,
            SpecialType.System_Int64 => 8,
            SpecialType.System_UInt64 => 8,
            SpecialType.System_Single => 4,
            SpecialType.System_Double => 8,
            SpecialType.System_Boolean => 1,
            _ => throw new InvalidOperationException(
                $"Unsupported primitive packet type '{type.ToDisplayString()}'.")
        };
    }

    /// <summary>
    /// Determines whether the specified type symbol represents a supported primitive numeric or boolean type.
    /// </summary>
    /// <param name="type">The type symbol to check.</param>
    /// <returns><see langword="true"/> if supported primitive; otherwise, <see langword="false"/>.</returns>
    private static bool IsPrimitive(
        ITypeSymbol type)
    {
        return type.SpecialType
            is SpecialType.System_Byte
            or SpecialType.System_SByte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Boolean;
    }

    /// <summary>
    /// Returns the name of the write method on <c>PacketWriter</c> corresponding to the specified primitive type.
    /// </summary>
    /// <param name="type">The primitive type symbol.</param>
    /// <returns>The writer method name.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the type is not supported.</exception>
    private static string GetWriteMethod(
        ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Byte => "WriteByte",
            SpecialType.System_SByte => "WriteSByte",
            SpecialType.System_Int16 => "WriteInt16",
            SpecialType.System_UInt16 => "WriteUInt16",
            SpecialType.System_Int32 => "WriteInt32",
            SpecialType.System_UInt32 => "WriteUInt32",
            SpecialType.System_Int64 => "WriteInt64",
            SpecialType.System_UInt64 => "WriteUInt64",
            SpecialType.System_Single => "WriteSingle",
            SpecialType.System_Double => "WriteDouble",
            SpecialType.System_Boolean => "WriteBoolean",
            _ => throw new InvalidOperationException(
                $"Unsupported generated field type '{type.ToDisplayString()}'.")
        };
    }

    /// <summary>
    /// Returns the name of the read method on <c>PacketReader</c> corresponding to the specified primitive type.
    /// </summary>
    /// <param name="type">The primitive type symbol.</param>
    /// <returns>The reader method name.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the type is not supported.</exception>
    private static string GetReadMethod(
        ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Byte => "ReadByte",
            SpecialType.System_SByte => "ReadSByte",
            SpecialType.System_Int16 => "ReadInt16",
            SpecialType.System_UInt16 => "ReadUInt16",
            SpecialType.System_Int32 => "ReadInt32",
            SpecialType.System_UInt32 => "ReadUInt32",
            SpecialType.System_Int64 => "ReadInt64",
            SpecialType.System_UInt64 => "ReadUInt64",
            SpecialType.System_Single => "ReadSingle",
            SpecialType.System_Double => "ReadDouble",
            SpecialType.System_Boolean => "ReadBoolean",
            _ => throw new InvalidOperationException(
                $"Unsupported generated field type '{type.ToDisplayString()}'.")
        };
    }

    /// <summary>
    /// Returns the C# keyword string for the underlying primitive type of an enum.
    /// </summary>
    /// <param name="type">The underlying primitive type symbol of the enum.</param>
    /// <returns>The C# keyword string.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the underlying type is unsupported.</exception>
    private static string GetPrimitiveTypeKeyword(
        ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            _ => throw new InvalidOperationException(
                $"Unsupported enum underlying type '{type.ToDisplayString()}'.")
        };
    }

    /// <summary>
    /// Formats the type symbol into a fully qualified C# source string.
    /// </summary>
    /// <param name="type">The type symbol to format.</param>
    /// <returns>The fully qualified type name string.</returns>
    private static string GetTypeName(
        ITypeSymbol type)
    {
        return type.ToDisplayString(
            TypeDisplayFormat);
    }

    /// <summary>
    /// Replaces non-alphanumeric characters in an identifier string with underscores to produce a valid C# identifier.
    /// </summary>
    /// <param name="value">The raw identifier candidate string.</param>
    /// <returns>A sanitized C# identifier string.</returns>
    private static string SanitizeIdentifier(
        string value)
    {
        StringBuilder builder =
            new(value.Length);

        foreach (char character in value)
        {
            builder.Append(
                char.IsLetterOrDigit(character) ||
                character == '_'
                    ? character
                    : '_');
        }

        return builder.ToString();
    }

    /// <summary>
    /// Computes a 64-bit Fowler-Noll-Vo (FNV-1a) hash for the given string to ensure deterministic unique naming.
    /// </summary>
    /// <param name="value">The string to hash.</param>
    /// <returns>The 64-bit unsigned hash value.</returns>
    private static ulong ComputeStableHash(
        string value)
    {
        const ulong offsetBasis =
            14695981039346656037UL;

        const ulong prime =
            1099511628211UL;

        ulong hash =
            offsetBasis;

        foreach (char character in value)
        {
            hash ^= character;
            hash *= prime;
        }

        return hash;
    }
}
